const DEFAULT_THEME = {
  bg: '#090b10',
  surface: '#111620',
  surface2: '#1a2230',
  text: '#ffffff',
  textDim: '#aab7cb',
  accent: '#efb738',
  accentLight: '#f6d56b',
  green: '#36d17c',
  squat: '#e14d43',
  bench: '#5e90d8',
  dead: '#b174d8',
  border: 'rgba(239,183,56,.24)',
  quote: '',
  cite: '',
  noteTitle: '',
  noteText: '',
  sourceFile: '',
}

export const athleteThemes =
  {
  "alexandre": {
    "bg": "#0a0a0f",
    "surface": "#14141f",
    "surface2": "#1c1c2a",
    "text": "#f0f0f8",
    "textDim": "#9090b0",
    "accent": "#ffd700",
    "accentLight": "#ffe54c",
    "green": "#00e676",
    "squat": "#ff4444",
    "bench": "#4488ff",
    "dead": "#44ff88",
    "border": "rgba(239,183,56,.24)",
    "quote": "« Échauffement terminé : opération caca prout officiellement lancée. Mise en place du bloc. »",
    "cite": "Rapport technique · S1 J1",
    "noteTitle": "Profil et maxes — Bloc 1",
    "noteText": "Athlète : Alexandre Poids : 74 kg Squat : 222,5 kg · Bench : 145 kg · Deadlift : 255 kg Total : 622,5 kg",
    "sourceFile": "Alexandre.html"
  },
  "guillaume": {
    "bg": "#080808",
    "surface": "#151515",
    "surface2": "#242424",
    "text": "#fff9ef",
    "textDim": "#d9d0c2",
    "accent": "#c83a2f",
    "accentLight": "#ff9a87",
    "green": "#70d19b",
    "squat": "#e14d43",
    "bench": "#5e90d8",
    "dead": "#b174d8",
    "border": "rgba(239,196,90,0.24)",
    "quote": "« Le trône ne se réclame pas : il se gagne, série après série, jusqu’à dépasser le rival que tout le monde pensait intouchable. »",
    "cite": "Anzalone — Objectif : dépasser Corentin Clément",
    "noteTitle": "👑 Conquête du trône — Bloc 4 semaines",
    "noteText": "Rivalité strictement sportive : dépasser Corentin Clément par les résultats, la technique et la constance.",
    "sourceFile": "Anzalone.html"
  },
  "benoit": {
    "bg": "#06120c",
    "surface": "#10241a",
    "surface2": "#193b29",
    "text": "#fff9e8",
    "textDim": "#d3dbc6",
    "accent": "#f1c85b",
    "accentLight": "#ffe8a0",
    "green": "#65e08d",
    "squat": "#f06d55",
    "bench": "#63a9ef",
    "dead": "#62da88",
    "border": "rgba(241,200,91,.34)",
    "variant": "sacred-emerald",
    "backgroundImage": "benoit-sacred-emerald.webp",
    "heroImage": "benoit-sacred-emerald.webp",
    "quote": "« Sois fort et prends courage : la constance passe avant l’ego. Mise en place du bloc. »",
    "cite": "Josué 1:9 · S1 J1",
    "noteTitle": "Profil et maxes",
    "noteText": "Athlète : Benoit Poids : 107 kg Squat : 240 kg · Bench : 160 kg · Deadlift : 280 kg Total : 680 kg",
    "sourceFile": "Benoit.html"
  },
  "celia": {
    "bg": "#11180f",
    "surface": "#1d2a1d",
    "surface2": "#2b3b29",
    "text": "#fff9e9",
    "textDim": "#d8dcc9",
    "accent": "#d9c58a",
    "accentLight": "#fff1bd",
    "green": "#8ed392",
    "squat": "#ed766d",
    "bench": "#6f9fd4",
    "dead": "#83ca8d",
    "border": "rgba(222,205,151,.28)",
    "variant": "french-cats",
    "backgroundImage": "celia-french-cats-universe.webp",
    "heroImage": "celia-french-cats-universe.webp",
    "quote": "« Ordre du jour : position, discipline, exécution. Le chat noir surveille la mission. Mise en place du bloc. »",
    "cite": "Ordre de mission · S1 J1",
    "noteTitle": "Profil et maxes",
    "noteText": "Athlète : Celia Poids : 63 kg Squat : 100 kg · Bench : 60 kg · Deadlift : 140 kg Total : 300 kg",
    "sourceFile": "Celia.html"
  },
  "charles": {
    "bg": "#090713",
    "surface": "#151022",
    "surface2": "#211934",
    "text": "#fff8dc",
    "textDim": "#d7c9e8",
    "accent": "#f4c542",
    "accentLight": "#ffe790",
    "green": "#58dda3",
    "squat": "#ff6d6d",
    "bench": "#75bfff",
    "dead": "#72e89c",
    "border": "rgba(239,183,56,.24)",
    "quote": "« Ecaflip lance les dés : aujourd’hui, la technique doit battre la chance. Mise en place du bloc. »",
    "cite": "Mise d’Ecaflip · S1 J1",
    "noteTitle": "Profil et maxes",
    "noteText": "Athlète : Charles Poids : 74 kg Squat : 200 kg · Bench : 125 kg · Deadlift : 220 kg Total : 545 kg",
    "sourceFile": "Charles.html"
  },
  "magicarpe": {
    "bg": "#06233b",
    "surface": "#0b3955",
    "surface2": "#12597b",
    "text": "#fffaf0",
    "textDim": "#cbeaf5",
    "accent": "#ff6a1a",
    "accentLight": "#ffd637",
    "green": "#4ee39b",
    "squat": "#ff5c35",
    "bench": "#18b9f2",
    "dead": "#ffd637",
    "border": "rgba(255,214,55,.38)",
    "variant": "lego-magicarpe",
    "headerKicker": "LEGO SPLASH QUEST · GA COACHING",
    "backgroundImage": "magicarpe-ocean.webp",
    "heroImage": "magicarpe-hero.webp",
    "sceneImage": "magicarpe-fishing.webp",
    "quote": "SPLASH ! Chaque série ajoute une brique à l’évolution de Magiclarpe.",
    "cite": "CLARA MAGICLARPE · OBJECTIF LÉVIATOR",
    "noteTitle": "Quête aquatique — Bloc de construction",
    "noteText": "Un univers coloré entre briques, océan et Magicarpe, réservé à la programmation de Clara.",
    "sourceFile": "ClaraMagiclarpe.html"
  },
  "clemosaurus": {
    "bg": "#080808",
    "surface": "#151515",
    "surface2": "#242424",
    "text": "#fff9ef",
    "textDim": "#d9d0c2",
    "accent": "#c83a2f",
    "accentLight": "#ff9a87",
    "green": "#70d19b",
    "squat": "#e14d43",
    "bench": "#5e90d8",
    "dead": "#b174d8",
    "border": "rgba(239,196,90,0.24)",
    "quote": "« La force se taille au long terme : on accumule, on confirme, puis on domine. »",
    "cite": "Clemosaurus — Objectif : bâtir la puissance",
    "noteTitle": "🦖 For the Emperor. For the Total.",
    "noteText": "Squat: 190 | Bench: 130 | Deadlift: 240 | Total: 560 \"Je puis tout par celui qui me fortifie.\" (Phil. 4:13) Even in death I still serve... des PR.",
    "sourceFile": "Clemosaurus.html"
  },
  "dorian": {
    "bg": "#080808",
    "surface": "#151515",
    "surface2": "#242424",
    "text": "#fff9ef",
    "textDim": "#d9d0c2",
    "accent": "#c83a2f",
    "accentLight": "#ff9a87",
    "green": "#70d19b",
    "squat": "#e14d43",
    "bench": "#5e90d8",
    "dead": "#b174d8",
    "border": "rgba(239,196,90,0.24)",
    "quote": "« Une séance propre, c’est un trick posé : de la constance, du rythme et zéro série lâchée. »",
    "cite": "Dorian — Objectif : enchaîner les sessions propres",
    "noteTitle": "🏀 NBA 2K 26 Mode MyCareer",
    "noteText": "Squat: 230 | Bench: 180 | Deadlift: 240 | Total: 650 Build: Glass Cleaning Finisher. La barre c'est le ballon, le rack c'est le panier. Typing shit only.",
    "sourceFile": "Dorian.html"
  },
  "duane": {
    "bg": "#080a0d",
    "surface": "#14181d",
    "surface2": "#20262d",
    "text": "#f4f2ed",
    "textDim": "#c7c9c8",
    "accent": "#ff4655",
    "accentLight": "#ffb2b9",
    "green": "#72d6a3",
    "squat": "#ff6d6d",
    "bench": "#75bfff",
    "dead": "#72e89c",
    "border": "rgba(239,183,56,.24)",
    "quote": "« Chaque série est une mission. Position, contrôle, exécution : aucun mouvement laissé au hasard. »",
    "cite": "Opération Barbe Noire — Bloc tactique",
    "noteTitle": "🪖 Opération Barbe Noire — Bloc 4 semaines",
    "noteText": "Direction artistique tactique inspirée des jeux d’agents, de la guerre moderne et d’une escouade de soldats barbus. Cinq missions hebdomadaires avec progression contrôlée sur le squat, le bench et le deadlift.",
    "sourceFile": "Duane.html"
  },
  "flop": {
    "bg": "#131b46",
    "surface": "#29366b",
    "surface2": "#4a5594",
    "text": "#fffaff",
    "textDim": "#e4def6",
    "accent": "#f5a9dd",
    "accentLight": "#fff0a8",
    "green": "#84e4c3",
    "squat": "#ff8eb8",
    "bench": "#7fdcff",
    "dead": "#bf9cff",
    "border": "rgba(239,210,255,.40)",
    "variant": "mew-dream",
    "headerKicker": "LE ROYAUME DE MEW · GA COACHING",
    "backgroundImage": "flop-mew-universe.webp",
    "heroImage": "flop-mew-universe.webp",
    "quote": "Dans le rêve de Mew, chaque série rapproche toute l’équipe de l’évolution.",
    "cite": "FLOP · LA TEAM DU NUAGE",
    "noteTitle": "Royaume de Mew — Bloc kawaii",
    "noteText": "Toute l’équipe de Flop réunie dans un univers pastel, magique et chaleureux inspiré de Mew.",
    "sourceFile": "Flop.html"
  },
  "hugo": {
    "bg": "#080a12",
    "surface": "#151827",
    "surface2": "#22273a",
    "text": "#f8f4e8",
    "textDim": "#d0cad8",
    "accent": "#8f63ff",
    "accentLight": "#d7c8ff",
    "green": "#60d394",
    "squat": "#ff6b6b",
    "bench": "#5fa8ff",
    "dead": "#b978ff",
    "border": "rgba(143,99,255,0.22)",
    "quote": "« Fais évoluer ta technique, construis ton deck et remporte chaque combat une répétition après l’autre. »",
    "cite": "Arène Hugo — Ligue des champions",
    "noteTitle": "⚡ Ligue Pokémon & Hearthstone — Bloc 4 semaines",
    "noteText": "Direction artistique inspirée des combats de créatures, des jeux vidéo et des parties de cartes stratégiques. Chaque séance fait progresser le personnage vers un rang supérieur.",
    "sourceFile": "Hugo.html"
  },
  "janel": {
    "bg": "#10070b",
    "surface": "#1a0e14",
    "surface2": "#28131d",
    "text": "#fff7f3",
    "textDim": "#decbd1",
    "accent": "#c69b55",
    "accentLight": "#f1d49a",
    "green": "#6ed39c",
    "squat": "#d65c68",
    "bench": "#7b8ce8",
    "dead": "#b66adb",
    "border": "rgba(239,183,56,.24)",
    "quote": "",
    "cite": "",
    "noteTitle": "Repères du bloc",
    "noteText": "Squat 135 kg · Bench 70 kg · Deadlift 180 kg · Total 385 kg · PDC 84 kg.",
    "sourceFile": "Janel2.html"
  },
  "jolan": {
    "bg": "#05081a",
    "surface": "#0e1530",
    "surface2": "#192652",
    "text": "#fbfdff",
    "textDim": "#c8d4ef",
    "accent": "#65ddff",
    "accentLight": "#f5dd79",
    "green": "#62ddb2",
    "squat": "#ff8068",
    "bench": "#65ddff",
    "dead": "#b08aff",
    "border": "rgba(109,221,255,.30)",
    "variant": "storm-king",
    "headerKicker": "ROI DES TEMPÊTES · GA COACHING",
    "backgroundImage": "jolan-gear5.webp",
    "heroImage": "jolan-yone.webp",
    "rivalImage": "jolan-yasuo.webp",
    "legacyImage": "jolan-lion-legacy.webp",
    "crestImage": "jolan-foncia.webp",
    "quote": "Libre comme l’éclair, précis comme une lame, solide comme un roi.",
    "cite": "JOLAN · LIBERTÉ, MAÎTRISE, HÉRITAGE",
    "noteTitle": "Le Royaume des Tempêtes — Bloc de conquête",
    "noteText": "Un univers mêlant Gear 5, les frères du vent, l’héritage du Roi Lion et la signature Foncia.",
    "sourceFile": "Jolan.html"
  },
  "jonathan": {
    "bg": "#07100e",
    "surface": "#101b18",
    "surface2": "#1b2b25",
    "text": "#fff6e8",
    "textDim": "#d6d0bf",
    "accent": "#d65a31",
    "accentLight": "#ffc2a8",
    "green": "#62c98d",
    "squat": "#ef6a4d",
    "bench": "#56b7d8",
    "dead": "#bd7cff",
    "border": "rgba(233,189,88,0.22)",
    "quote": "« Avance avec la force des Hautes Terres, la patience des baobabs et l’énergie de l’île rouge. »",
    "cite": "Expédition Jonathan — Madagascar",
    "noteTitle": "🌴 Expédition Madagascar — Bloc 4 semaines",
    "noteText": "Direction artistique inspirée de l’île rouge, des Hautes Terres, des lémuriens, des baobabs, des côtes sauvages et des couleurs tropicales.",
    "sourceFile": "Jonathan.html"
  },
  "kaoutar": {
    "bg": "#0b0908",
    "surface": "#171210",
    "surface2": "#261b18",
    "text": "#fff7e9",
    "textDim": "#d9cec2",
    "accent": "#c1272d",
    "accentLight": "#f4a5a8",
    "green": "#1f8f5f",
    "squat": "#ef6a5b",
    "bench": "#4aa8d8",
    "dead": "#b978ff",
    "border": "rgba(227,180,81,0.24)",
    "quote": "« Avance avec la solidité de l’Atlas, la précision du zellige et l’énergie du Royaume 6-7. »",
    "cite": "Kaoutar — Parcours Maroc 6-7",
    "noteTitle": "🇲🇦 Kaoutar — Bloc 2",
    "noteText": "Nouveau bloc de 4 semaines orienté muscle-up, street lifting et SBD.",
    "sourceFile": "Kaoutar2.html"
  },
  "killian": {
    "bg": "#070b12",
    "surface": "#111925",
    "surface2": "#1b2737",
    "text": "#f7f4e8",
    "textDim": "#c9d0d9",
    "accent": "#c89b3c",
    "accentLight": "#f0d58a",
    "green": "#48c78e",
    "squat": "#ef6f63",
    "bench": "#58a6ff",
    "dead": "#ad7cff",
    "border": "rgba(200,155,60,0.24)",
    "quote": "« Le prix est ce que tu paies. La valeur est ce que tu obtiens. »",
    "cite": "Warren Buffett — principe d’investissement",
    "noteTitle": "🏆 Portefeuille de la Faille — Bloc 4 semaines",
    "noteText": "Direction artistique mêlant League of Legends, marchés financiers, construction de capital et investissement à long terme. Chaque séance représente une nouvelle position dans le portefeuille de performance.",
    "sourceFile": "Killian2.html"
  },
  "lou": {
    "bg": "#080808",
    "surface": "#151515",
    "surface2": "#242424",
    "text": "#fff9ef",
    "textDim": "#d9d0c2",
    "accent": "#c83a2f",
    "accentLight": "#ff9a87",
    "green": "#70d19b",
    "squat": "#e14d43",
    "bench": "#5e90d8",
    "dead": "#b174d8",
    "border": "rgba(239,196,90,0.24)",
    "quote": "« Nouveau bloc : on garde la base et on pousse la progression sur quatre semaines. »",
    "cite": "Lou — Programme 2",
    "noteTitle": "🏍️ Moto x Chats x Techno",
    "noteText": "Squat: 100 | Bench: 59 | Deadlift: 120 | Total: 279 PDC: 58.7kg. Le moteur est petit mais il tourne à fond.",
    "sourceFile": "Lou2.html"
  },
  "louis": {
    "bg": "#04130e",
    "surface": "#0d2b20",
    "surface2": "#174634",
    "text": "#f5fff8",
    "textDim": "#c6e5d3",
    "accent": "#45ef71",
    "accentLight": "#b8ff72",
    "green": "#4dff9a",
    "squat": "#ff765f",
    "bench": "#55bfff",
    "dead": "#4dff91",
    "border": "rgba(87,239,139,.34)",
    "variant": "emerald-realm",
    "headerKicker": "EMERALD REALM · GA COACHING",
    "backgroundImage": "louis-emerald-universe.webp",
    "heroImage": "louis-emerald-universe.webp",
    "quote": "Play. Fuel. Grow. Belong.",
    "cite": "LOUIS · EMERALD REALM",
    "noteTitle": "Emerald Realm — Bloc de Louis",
    "noteText": "Un univers de jeu en blocs porté par l’énergie du dragon émeraude. Chaque séance fait progresser le personnage, la maîtrise et la puissance de Louis.",
    "sourceFile": "Louis (2).html"
  },
  "lucine": {
    "bg": "#07100c",
    "surface": "#111d17",
    "surface2": "#1b2b22",
    "text": "#fff8e9",
    "textDim": "#d8d1bd",
    "accent": "#78b85a",
    "accentLight": "#d1f0ad",
    "green": "#69ce91",
    "squat": "#ed7f6d",
    "bench": "#78b9ef",
    "dead": "#ba8de8",
    "border": "rgba(239,198,90,0.23)",
    "quote": "« Une belle récolte commence par de petites actions répétées avec soin, jour après jour. »",
    "cite": "La ferme de Lucine — Petit chat & vallée étoilée",
    "noteTitle": "🌱 Ferme de Lucine — Bloc 4 semaines",
    "noteText": "Direction artistique inspirée d’un petit chat, de la vie à la ferme, des saisons et de Stardew Valley. La progression est présentée comme une récolte construite semaine après semaine.",
    "sourceFile": "Lucine.html"
  },
  "malo": {
    "bg": "#080a10",
    "surface": "#141823",
    "surface2": "#202838",
    "text": "#fff7e8",
    "textDim": "#d2ccbf",
    "accent": "#ef7d28",
    "accentLight": "#ffc27b",
    "green": "#6ed59b",
    "squat": "#ff6f59",
    "bench": "#5ea9ff",
    "dead": "#af7cff",
    "border": "rgba(241,196,79,0.24)",
    "quote": "« La force transmise par ton coach devient une flamme : à toi de l’entretenir, de la maîtriser et de la dépasser. »",
    "cite": "Malo — Héritier de la flamme et du ki",
    "noteTitle": "🐉 Héritage du coach — Bloc 4 semaines",
    "noteText": "Direction artistique mêlant Dragon Ball, énergie du ki, braises de Dark Souls et transmission entre le coach et son successeur. Chaque séance représente une étape vers une forme plus forte.",
    "sourceFile": "Malo.html"
  },
  "marvin": {
    "bg": "#090807",
    "surface": "#161311",
    "surface2": "#241e1a",
    "text": "#fff7eb",
    "textDim": "#d8c9bb",
    "accent": "#e74f3f",
    "accentLight": "#ffb59a",
    "green": "#67d497",
    "squat": "#ff715f",
    "bench": "#6da6ff",
    "dead": "#b78cff",
    "border": "rgba(231,79,63,0.22)",
    "quote": "« T’avais dit que t’étais pas une salope. Alors termine ce que t’as commencé. »",
    "cite": "Engagement · S1 J1",
    "noteTitle": "Profil et maxes",
    "noteText": "Athlète : Marvin Slug Supabase : marvin Genre : Homme Poids de référence : 83 kg Squat : 270 kg · Bench : 175 kg · Deadlift : 270 kg Total SBD : 715 kg.",
    "sourceFile": "Marvin.html"
  },
  "matthieu": {
    "bg": "#07100b",
    "surface": "#121d17",
    "surface2": "#1c2c22",
    "text": "#fff9e9",
    "textDim": "#d5d1be",
    "accent": "#4cad5c",
    "accentLight": "#bdebbd",
    "green": "#66d49a",
    "squat": "#ef7865",
    "bench": "#62aeed",
    "dead": "#d2a34a",
    "border": "rgba(240,200,77,0.24)",
    "quote": "« La spécialisation ne consiste pas à répéter sans réfléchir, mais à transformer chaque tirage en compétence maîtrisée. »",
    "cite": "Matthieu — Hunter du deadlift",
    "noteTitle": "🎣 Parcours du Hunter — Bloc 4 semaines",
    "noteText": "Direction artistique inspirée de Gon, de la nature, des épreuves de Hunter et d’une spécialisation assumée sur le deadlift. La progression met l’accent sur la force de tirage, le contrôle et la régularité.",
    "sourceFile": "Matthieu.html"
  },
  "maxence": {
    "bg": "#080a10",
    "surface": "#141722",
    "surface2": "#202637",
    "text": "#fff8e8",
    "textDim": "#d5ccbb",
    "accent": "#244e9b",
    "accentLight": "#9fbaff",
    "green": "#69ce95",
    "squat": "#d96557",
    "bench": "#629bea",
    "dead": "#a477df",
    "border": "rgba(231,188,80,0.25)",
    "quote": "« Un roi ne conquiert pas une autre comté par hasard : il observe, il tient sa position et il frappe au bon moment. »",
    "cite": "Maxence — Le roi Nœil d’une autre comté",
    "noteTitle": "👑 Chroniques du roi Nœil",
    "noteText": "Direction artistique inspirée d’un roi venu d’une autre comté : bleu royal, or, bordeaux, pierre et blasons. Chaque séance représente une étape de conquête fondée sur la posture, le contrôle et la précision.",
    "sourceFile": "Maxence.html"
  },
  "metaknight": {
    "bg": "#080810",
    "surface": "#151523",
    "surface2": "#24243a",
    "text": "#fff8ec",
    "textDim": "#d7cfe2",
    "accent": "#7456c8",
    "accentLight": "#c8b7ff",
    "green": "#72d69d",
    "squat": "#ef7284",
    "bench": "#73aaff",
    "dead": "#a77be8",
    "border": "rgba(239,196,90,0.24)",
    "quote": "« Nouveau bloc conservé séparément du programme précédent : progression sur quatre semaines, sans effacer le Bloc 1. »",
    "cite": "Metaknight — Programme 2",
    "noteTitle": "🐈 Captain Grassou — Bloc 4 semaines",
    "noteText": "Direction artistique inspirée des chats, d’un chevalier violet et de Captain Grassou, beaucoup trop smooth pour perdre son calme. Chaque séance devient une mission pour protéger Mew.",
    "sourceFile": "Metaknight2.html"
  },
  "noe": {
    "bg": "#071018",
    "surface": "#101d28",
    "surface2": "#1a2d3c",
    "text": "#f6fbff",
    "textDim": "#c8d7e1",
    "accent": "#22b8cf",
    "accentLight": "#a9f2ff",
    "green": "#68d79f",
    "squat": "#ef7482",
    "bench": "#62a7ff",
    "dead": "#9d79e7",
    "border": "rgba(239,196,90,0.24)",
    "quote": "« La Brotherhood ne laisse personne derrière : chaque série réussie maintient Jolan debout. »",
    "cite": "Noé — Gardien du Wakfu et frère de combat",
    "noteTitle": "🌀 Brotherhood — Bloc 4 semaines",
    "noteText": "Direction artistique inspirée de Wakfu, du Monde des Douze, des portails énergétiques et de la fraternité. Chaque séance est une mission destinée à maintenir l’équipe unie et à protéger Jolan.",
    "sourceFile": "Noe.html"
  },
  "sarah": {
    "bg": "#040717",
    "surface": "#101633",
    "surface2": "#231747",
    "text": "#fffaff",
    "textDim": "#d8d7ef",
    "accent": "#ff4db8",
    "accentLight": "#ffd765",
    "green": "#74e7cb",
    "squat": "#ff617d",
    "bench": "#58b8ff",
    "dead": "#b06cff",
    "border": "rgba(126,174,255,.34)",
    "variant": "cosmic-ascension",
    "headerKicker": "ASCENSION COSMIQUE · GA COACHING",
    "backgroundImage": "sarah-cosmic-universe.webp",
    "heroImage": "sarah-cosmic-universe.webp",
    "quote": "Chaque série libère une nouvelle forme de puissance.",
    "cite": "SARAH · COSMIC ASCENSION",
    "noteTitle": "Ascension cosmique — Bloc de Sarah",
    "noteText": "Une progression entre puissance, maîtrise et énergie cosmique. Chaque séance fait évoluer l’univers de Sarah sans jamais gêner la lecture du programme.",
    "sourceFile": "Sarah.html"
  },
  "saya": {
    "bg": "#09070d",
    "surface": "#17121d",
    "surface2": "#281d31",
    "text": "#fff8f2",
    "textDim": "#ddcedd",
    "accent": "#9b3fc2",
    "accentLight": "#e4b4ff",
    "green": "#6dd39c",
    "squat": "#e35d54",
    "bench": "#687fe8",
    "dead": "#b45dde",
    "border": "rgba(239,195,90,0.24)",
    "quote": "« Nouveau bloc préparé sans effacer le programme actuellement en cours. »",
    "cite": "Saya — Programme 2",
    "noteTitle": "🌋 Pouvoir de La Réunion",
    "noteText": "Direction artistique inspirée du volcan, de l’océan Indien, de l’amour absolu et d’une présence d’antagoniste ultime. Le personnage reste calme, magnétique et convaincu de pouvoir protéger les siens en contrôlant tout ce qui l’entoure.",
    "sourceFile": "Saya2.html"
  },
  "serena": {
    "bg": "#080b18",
    "surface": "#14182a",
    "surface2": "#232941",
    "text": "#fff9f4",
    "textDim": "#d8d5e6",
    "accent": "#8d62d9",
    "accentLight": "#dbc8ff",
    "green": "#72d49d",
    "squat": "#ef728d",
    "bench": "#6d9df2",
    "dead": "#b678e7",
    "border": "rgba(242,200,95,0.25)",
    "quote": "« Les plus belles promesses se font sous les lumières du château, mais les plus grandes preuves de force se donnent sur la barre. »",
    "cite": "Serena — Princesse et spécialiste du deadlift",
    "noteTitle": "🏰 Royaume enchanté — Bloc 4 semaines",
    "noteText": "Direction artistique inspirée de Disneyland, des châteaux illuminés, des demandes en mariage et d’une spécialiste du deadlift. Chaque séance représente une étape vers la grande parade finale.",
    "sourceFile": "Serena.html"
  },
  "tom": {
    "bg": "#06111b",
    "surface": "#0d1d2a",
    "surface2": "#163044",
    "text": "#f7fcff",
    "textDim": "#bdd2df",
    "accent": "#75d9ff",
    "accentLight": "#e2f8ff",
    "green": "#5ee0b1",
    "squat": "#ff7b72",
    "bench": "#75d9ff",
    "dead": "#b9eaff",
    "border": "rgba(151,225,255,.30)",
    "variant": "north-strength",
    "headerKicker": "THE NORTH STRENGTH · GA COACHING",
    "backgroundImage": "tom-north-forest.webp",
    "logoImage": "tom-north-logo.webp",
    "mascotImage": "tom-polar-bear.webp",
    "quote": "« Le froid ne ralentit pas la force : il la forge. Chaque répétition laisse une trace dans le Nord. »",
    "cite": "THE NORTH STRENGTH · TOM DENEUVILLE",
    "noteTitle": "Territoire du Nord — Bloc de force",
    "noteText": "Une programmation construite autour de la maîtrise, de la puissance et de la constance.",
    "sourceFile": "TomDeneuville.html"
  },
  "gibertini": {
    "bg": "#070b12",
    "surface": "#111926",
    "surface2": "#1b2938",
    "text": "#f7f3e8",
    "textDim": "#c9d0d8",
    "accent": "#6ecbff",
    "accentLight": "#c7ecff",
    "green": "#69d59c",
    "squat": "#ff7d69",
    "bench": "#6ecbff",
    "dead": "#b388ff",
    "border": "rgba(110,203,255,0.20)",
    "quote": "« Prépare ton équipement, maîtrise ta technique et traque chaque répétition comme une quête de rang maître. »",
    "cite": "Guilde Gibertini — Contrat Monster Hunter",
    "noteTitle": "🐉 Contrat Monster Hunter — Bloc 4 semaines",
    "noteText": "Direction artistique inspirée de Monster Hunter et des grands RPG PlayStation : quêtes, rangs, forge, expéditions et chasse finale.",
    "sourceFile": "Tom.html"
  },
  "yann": {
    "bg": "#0b0905",
    "surface": "#1b140b",
    "surface2": "#2c2112",
    "text": "#fffaf0",
    "textDim": "#e3d5b5",
    "accent": "#e59a23",
    "accentLight": "#ffd77a",
    "green": "#77d59f",
    "squat": "#eb633f",
    "bench": "#5f91db",
    "dead": "#b16bd8",
    "border": "rgba(255,210,79,0.27)",
    "quote": "« WHO DECIDED THAT ? »",
    "cite": "Yannick — The One, personnage surpuissant",
    "noteTitle": "☀️ The One — Bloc 4 semaines",
    "noteText": "Direction artistique inspirée d’Escanor et des personnages d’anime surpuissants. La puissance augmente avec la séance jusqu’à atteindre sa forme maximale lors du travail intense.",
    "sourceFile": "Yannick.html"
  }
}

function normalizeKey(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
}

function colorSoft(
  value,
  alpha = .16
) {
  const color =
    String(value || '')
      .trim()

  const match =
    color.match(
      /^#([0-9a-f]{{6}})$/i
    )

  if (!match) {
    return 'rgba(239,183,56,.16)'
  }

  const hex =
    match[1]

  const red =
    Number.parseInt(
      hex.slice(0,2),
      16
    )

  const green =
    Number.parseInt(
      hex.slice(2,4),
      16
    )

  const blue =
    Number.parseInt(
      hex.slice(4,6),
      16
    )

  return `rgba(${red},${green},${blue},${alpha})`
}

export function getAthleteTheme(
  athleteSlug
) {
  const key =
    normalizeKey(
      athleteSlug
    )

  return {
    ...DEFAULT_THEME,
    ...(
      athleteThemes[key] ||
      {}
    ),
  }
}

export function athleteThemeStyle(
  theme
) {
  const current = {
    ...DEFAULT_THEME,
    ...(theme || {}),
  }

  return [
    `--athlete-bg:${current.bg}`,
    `--athlete-surface:${current.surface}`,
    `--athlete-surface-2:${current.surface2}`,
    `--athlete-text:${current.text}`,
    `--athlete-text-dim:${current.textDim}`,
    `--athlete-accent:${current.accent}`,
    `--athlete-accent-light:${current.accentLight}`,
    `--athlete-accent-soft:${colorSoft(current.accent,.16)}`,
    `--athlete-accent-soft-2:${colorSoft(current.accent,.28)}`,
    `--athlete-green:${current.green}`,
    `--athlete-squat:${current.squat}`,
    `--athlete-bench:${current.bench}`,
    `--athlete-dead:${current.dead}`,
    `--athlete-border:${current.border}`,
    `--athlete-theme-background-image:${current.backgroundImage ? `url(${current.backgroundImage})` : 'none'}`,
  ].join(';')
}
